---
- hosts: webservers
  sudo: yes

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service
    service: name=httpd enabled=yes state=started
 
  - name: Copy zar File
    copy:
      src=/var/lib/jenkins/workspace/Pipeline/dileep.jar
      dest=/home/ec2-user/dileep.jar
      remote_src=yes
  
- hosts: dbservers
  sudo: yes

  tasks:
  - name: Copy zar File
    copy:
      src=/var/lib/jenkins/workspace/Pipeline/dileep.jar
      dest=/home/ec2-user/dileep.jar
      remote_src=yes
      
