---
- hosts: webservers
  sudo: yes

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service
    service: name=httpd enabled=yes state=started
 
  - name: Copy zar File
    template: src=dileep.zar dest=/home/ec2-user/dileep.zar
  
- hosts: dbservers
  sudo: yes

  tasks:
  - name: Copy zar File
    template: src=dileep.zar dest=/home/ec2-user/dileep.zar
